import { SEOHead } from "@/components/SEOHead";
import { Footer } from "@/components/Footer";

const examples = [
  {
    title: "Intro to Biology Lecture",
    description: "Sample video generated from lecture notes using English voice.",
    url: "https://yourdomain.com/outputs/videos/sample-bio.mp4",
    thumbnail: "/og-image.png",
    uploadDate: "2024-01-01",
    duration: "PT2M30S",
  },
];

const Examples = () => {
  const siteUrl = (import.meta as any).env?.VITE_SITE_URL || "https://yourdomain.com";
  const canonical = `${siteUrl}/examples`;
  const videoObjects = examples.map((e) => ({
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: e.title,
    description: e.description,
    thumbnailUrl: [e.thumbnail],
    contentUrl: e.url,
    uploadDate: e.uploadDate,
    duration: e.duration,
  }));

  return (
    <div className="min-h-screen bg-gradient-to-b from-white via-gray-50 to-white dark:from-gray-950 dark:via-gray-900 dark:to-gray-950">
      <SEOHead
        title="AI Lecture Examples"
        description="See example AI-generated lecture videos created from study notes."
        url={canonical}
        canonical={canonical}
        schemaMarkup={videoObjects}
      />
      <section className="relative max-w-7xl mx-auto px-6 pt-24 pb-16 overflow-hidden">
        <div className="absolute top-0 -left-48 w-96 h-96 bg-blue-500/10 dark:bg-blue-500/5 rounded-full blur-3xl" />
        <div className="relative z-10">
          <h1 className="text-5xl md:text-7xl font-bold text-black dark:text-white mb-6 leading-tight">
            <span className="bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 bg-clip-text text-transparent">Examples</span>
          </h1>
          <p className="text-lg md:text-2xl text-gray-600 dark:text-gray-400 max-w-3xl leading-relaxed">
            Explore example lectures generated by PreplitAI.
          </p>
        </div>
        <div className="mt-10 grid md:grid-cols-2 gap-6">
          {examples.map((ex) => (
            <article key={ex.title} className="p-6 rounded-2xl border border-gray-200 dark:border-gray-800">
              <h3 className="text-xl font-semibold text-black dark:text-white">{ex.title}</h3>
              <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">{ex.description}</p>
              <a className="mt-3 inline-block text-blue-600 dark:text-blue-400" href={ex.url}>View sample</a>
            </article>
          ))}
        </div>
      </section>
      <Footer />
    </div>
  );
};

export default Examples;